sudo: false
language: cpp
addons:
  apt:
    packages:
       # Compilers
      - g++
      - gfortran
      - cmake
        # Libraries for static linking
      - binutils-gold
      - libc6-dev
      - libpthread-stubs0-dev
        # Math libraries
      - libblas-dev
      - libatlas-base-dev
      - libatlas-dev
      - libatlas3gf-base
        # MPI
      - openmpi-bin
      - libopenmpi-dev
        # Python library, development version
      - libpython2.7
before_script:
  - export PATH=$HOME/.local/bin:$PATH
    # PEP8 and py.test
  - pip install pytest pep8 --user `whoami`
  - dpkg -S clapack.h
  - dpkg -S cblas.h
script:
    # test PEP8 conformity
  - pep8 --ignore=E501 update.py
  - pep8 --ignore=E501 test/test.py
  - pep8 --ignore=E501 lib/config.py
    # run unit tests
  - py.test -vv update.py
  - py.test -vv test/test.py
  - py.test -vv lib/config.py

notifications:
  email: false
